from setuptools import setup, find_packages

setup(
    name='TractoPL',
    version='0.1.0',
    author='Nathan Decaux',
    author_email='nathan.decaux@hotmail.fr',
    description='Tractometry processing library for diffusion MRI data.',
    long_description=open('README.md').read(),
    long_description_content_type='text/markdown',
    url='https://github.com/nathandecaux/TractoPL',
    packages=find_packages(),
    entry_points={
        'console_scripts': [
            'tractopl-apply-trans-to-vtk=TractoPL.scripts.apply_trans_to_vtk:main',
            'tractopl-convert-tractogram=TractoPL.scripts.convert_tractogram:main',
            'tractopl-frechet-clustering=TractoPL.atlasing.frechet_clustering:main',
            'tractopl-generate-centroid=TractoPL.atlasing.generate_centroid:main',
            'tractopl-afq-analysis=TractoPL.analysis.AFQ_analysis:main',
            'tractopl-preprocessing=TractoPL.pipeline.preprocessing:cli',
            'tractopl-msmt-csd=TractoPL.pipeline.msmt_csd:process_subject',
            'tractopl-mcm=TractoPL.pipeline.mcm:cli',
            'tractopl-bundle-seg=TractoPL.pipeline.bundle_seg:main',
            'tractopl-tractometry=TractoPL.pipeline.tractometry:association',
            'tractopl-connectome=TractoPL.pipeline.connectome:cli',
        ],
    },
    install_requires=[
        'antspyx',
        'click',
        'dipy',
        'pandas',
        'numpy',
        'matplotlib',
        'nibabel',
        'pydicom',
        'scipy',
        'shapely',
        'SimpleITK',
        'tqdm',
        'vtk',
        'lpqtree',
    ],
    extras_require={
        'dashboard': ['plotly', 'statsmodels', 'streamlit'],
        'dev': ['pytest'],
    },
    package_data={'TractoPL': ['config_profiles/*.json']},
    classifiers=[
        'Programming Language :: Python :: 3',
        'Operating System :: OS Independent',
    ],
    python_requires='>=3.6',
)